//Project URL: http://projecteuler.net/problem=2
//Even Fibonacci numbers
//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


var fb1 = 0;
var fb2 = 1;
var fb3;
var sum = 0;


while ( fb1 < input ){						//fb1 is the incremental number that gets added up to the input, not the sum 
  if ( fb1 % 2 === 0 ){
    	sum += fb1;
	}
	fb3 = fb1 + fb2;
	fb1 = fb2;
	fb2 = fb3;
}

//fb1	fb2	fb3	sum
//0		1		1		2
//1		1		1		3
//1		2		2		5
//2		3		3		8
//3		5		5		13
//5		8		8		21

var input = 4000000;
console.log(sum);
